version: 1.0.2.12

signing:
  debug:
    store: $MOD_HOME/ingress-indonesia-dev/res/ingress-mod.keystore
    pass: qwerty
    alias: ingress_mod

  release:
    store: $MOD_HOME/ingress-indonesia-dev/res/ingress-mod.keystore
    pass: qwerty
    alias: ingress_mod

maps_key:
  debug: AIzaSyDnBplgAJZudNKNy7n2xwfvcHnrZuVVGsk
  release: AIzaSyDnBplgAJZudNKNy7n2xwfvcHnrZuVVGsk
